# This will control the amount of maximum hearts/health the player can get.
Max health: '40'
# This will give a bow that teleports the player to wherever the arrow lands as soon as the player joins the server.
give-bow-on-join: true
# This will change the name of the bow given when /tpbow is used, or when a player joins the server
# (if give-bow-on-join is true)
bow-name: '&f[&eTeleport&aBow&f]'
# This will change the description of the bow given when /tpbow is used, or when a player joins the server
# (if give-bow-on-join is true)
bow-description: '&6Shoot your shot..'
# This will control wether turtles will spawn when a player moves.
# This will be very laggy.
turtle-spam: false
# This is the message that will be sent to the player once they're done creating an armorstand.
create-message: '&6Created armor stand.'
# If you have a world border in your server, enable this and check next option.
world-border: true
# If world-border is set to true, make this whatever your world border is set to.
border: 200
# Will send a message in console every 5 seconds. If true, check the next option.
send-message: false
# Choose what you want your message to be.
scheduled-message: '&cTask run successfully'
# If you want to keep the weather clear and time at day at all times, set this to true.
perfect-day: true
# If "perfect-day" is set to true, change this to the name of your world.
world-name: 'world'
# If you want an MOTD, set this to true and check the next option.
motd: true
# Select the MOTDs you want to be shown.
motd-messages:
  - '&cwowo its a motd!'
  - '&6oh em jee'
  - '&bhello socks'
  - 'https://nohello.net/'